### PR TITLE
Tc001 taho added lastGithub class

### PR DESCRIPTION
**Pull request by tahsnerken47**

### CODE REVIEW

**Review by sdet46 — COMMENTED** [review]
Good Job Tahsin

**Review by NozaM8 — COMMENTED** [review]
need to add more lines of code. But good job anyways

**Comment by tahsnerken47** [comment]
Thank u @isa can approve my request

**Review by NozaM8 — APPROVED** [review]

**Comment by tahsnerken47** [comment]
Good job guys

**Comment by sdet46** [comment]
89352699_10157844008581480_3864317118572920832_o

Just Testing

**Pull request merged**
